stages:
  sync_bio_sent:
    cmd: docker-compose run ml.thageesan python -m ai.data.sync_bio_sent .
    deps:
    - ai/data/sync_bio_sent/__init__.py
    outs:
    - data/bioSent2Vec.bin
  positive_train_samples:
    cmd: docker-compose run ml.thageesan python -m ai.data.positive_train_samples
      .
    deps:
    - ai/data/positive_train_samples/__init__.py
    outs:
    - data/df_positive_w_id_for_train_and_stats.csv
  negative_train_samples_train_samples:
    cmd: docker-compose run ml.thageesan python -m ai.data.negative_train_samples
      .
    deps:
    - ai/data/negative_train_samples/__init__.py
    outs:
    - data/df_negative_for_train_and_stats.csv
  snippet_database:
    cmd: docker-compose run ml.thageesan python -m ai.data.snippet_database .
    deps:
    - ai/data/snippet_database/__init__.py
    outs:
    - data/cleaned_snippets_with_org_name_new_rows.csv
