stages:
  sync_negative_train_samples:
    cmd: aws s3 cp s3://ezra-ml-dvc/reporter/df_negative_for_train_and_stats.csv ./data/df_negative_for_train_and_stats.csv
    deps:
    - s3://ezra-ml-dvc/reporter/df_negative_for_train_and_stats.csv
    outs:
    - data/df_negative_for_train_and_stats.csv
  sync_positive_train_samples:
    cmd: aws s3 cp s3://ezra-ml-dvc/reporter/df_positive_w_id_for_train_and_stats.csv
      ./data/df_positive_w_id_for_train_and_stats.csv
    deps:
    - s3://ezra-ml-dvc/reporter/df_positive_w_id_for_train_and_stats.csv
    outs:
    - data/df_positive_w_id_for_train_and_stats.csv
  sync_snippet_database:
    cmd: aws s3 cp s3://ezra-ml-dvc/reporter/cleaned_snippets_with_org_name_new_rows.csv
      ./data/cleaned_snippets_with_org_name_new_rows.csv
    deps:
    - s3://ezra-ml-dvc/reporter/cleaned_snippets_with_org_name_new_rows.csv
    outs:
    - data/cleaned_snippets_with_org_name_new_rows.csv
