---

- hosts: localhost
  gather_facts: false

  tasks:
    - import_tasks: local_environment_check.yml

    - name: Add hosts
      add_host:
        name: "{{item}}"
        group: [ local_dev_servers ]
      with_items: "{{ instance_query_results.instances | map(attribute='private_ip_address') }}"
      when: instance_query_results.instances | map(attribute='private_ip_address') | length > 0

- hosts: local_dev_servers
  remote_user: ec2-user
  gather_facts: false

  tasks:
    - debug:

    - name: Install yum packages
      yum:
        name: "{{ packages }}"
        state: latest
      become: yes
      vars:
        packages:
          - python3-devel
          - gcc-c++
          - pkgconfig
          - poppler-cpp-devel
    
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /home/ec2-user/reporter_repo
        state: directory
        recurse: yes
        owner: ec2-user
        group: ec2-user
        mode: '0755'
      become: yes

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3

    - name: Install invoke
      pip:
        name: invoke
        executable: pip3


    - name: Install specified python requirements
      pip:
        requirements: /home/ec2-user/reporter_repo/requirements.txt
        executable: pip3

    - name: Sync Model
      shell: /home/ec2-user/.local/bin/invoke --search-root="/home/ec2-user/reporter_repo" modelsync
      args:
        chdir: /home/ec2-user/reporter_repo
        
        